apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    type: location
  name: locationdeployment
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/locationdeployment
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      type: location
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        type: location
    spec:
      containers:
      - image: upigrad82/location
        imagePullPolicy: Always
        name: location
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
          - name: FNAME_ENV_VAR
            valueFrom:
              configMapKeyRef:
                name: myconfigmap
                key: fname
          - name: SNACK_ENV_VAR
            valueFrom:
              configMapKeyRef:
                name: myconfigmap
                key: snack
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
